import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About — Matthew Raya Steinbeiss",
  description:
    "Matthew Raya Steinbeiss is an artist, musician, and maker working in the space between the organic and the synthesized.",
};

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-5xl px-6 py-24">
      <div className="max-w-2xl">
        <h1 className="mb-12 font-serif text-4xl italic text-foreground">
          About
        </h1>

        <div className="space-y-6 text-muted">
          <p className="text-lg text-foreground">
            I make things that live in the space between the organic and the
            synthesized — between a sound you feel in your chest and one that
            exists only in headphones, between a mark made by hand and a form
            generated by process.
          </p>

          <p>
            I have been playing music since I was eleven. Guitar, bass,
            keyboards, synthesizers, audio engineering — the instrument has
            always mattered less than what it could do. That restlessness
            carries through into everything else: three music projects with
            distinct identities, a visual art practice that moves between
            precise botanical drawing and fluid abstract painting, woodworking,
            and 3D printing.
          </p>

          <p>
            The through-line is a belief that made things — carefully,
            intentionally made things — can create genuine connection between
            people. Not connection as a product feature, but as a physical and
            auditory fact. Something you hold, or something that changes the
            room you&apos;re in.
          </p>

          <p>
            The work is &ldquo;trippy&rdquo; in the sense that it tries to
            unsettle the familiar — but it isn&apos;t trying to belong to any
            particular genre or movement. The acrylic pours look like something
            geological or cosmic without being either. The music reaches for
            something genuinely felt without being nostalgic about the analog or
            uncritical about the digital. The objects are useful and strange at
            the same time.
          </p>

          <p>
            The goal, across all of it, is the same: to make something beautiful
            that improves someone&apos;s life, even briefly.
          </p>
        </div>

        <div className="mt-16 border-t border-border pt-10">
          <h2 className="mb-6 font-serif text-2xl italic text-foreground">
            Projects
          </h2>
          <div className="space-y-4">
            {[
              {
                name: "The Slow Sink",
                description:
                  "Acoustic and synthesized songwriting. The most personal project.",
              },
              {
                name: "Matthew Ashed",
                description:
                  "Electronic music — dance-oriented and headphone-oriented in equal measure.",
              },
              {
                name: "Constraints",
                description:
                  "Ambient music. Wide, slow, immersive. Limitation as a compositional force.",
              },
              {
                name: "@mindovermaffer",
                description:
                  "Visual art — acrylic painting, pen and ink, photography, and more.",
              },
            ].map(({ name, description }) => (
              <div key={name} className="flex gap-6">
                <span className="w-40 shrink-0 font-serif italic text-foreground">
                  {name}
                </span>
                <span className="text-muted">{description}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
